server:
  port: 8060
cxf:
  path: /soap
pensjon:
  testdata:
    url: http://localhost:3000
ldap:
  server:
    enabled: true
    port: 8389
    securePort: 8636
management:
  endpoints:
    web:
      exposure:
        include: "*"
verbose: false
