name: Bygg og deploy

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

env:
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/vtp-pensjon
  IMAGE_BASE_GHCR: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Cache SonarCloud packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

#      - name: Cache Docker layers
#        uses: actions/cache@v2.1.4
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-

      - uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build and analyze
        shell: bash
        run: |
          mvn -T1C verify --settings maven-settings.xml -Dfile.encoding=UTF-8 -Dkotlin.format.skip=true -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker image
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=12 HEAD)
          export VERSION="$TIME-$COMMIT"
          echo "Building version $VERSION"

          docker build --pull \
            --tag ${IMAGE_BASE}:${VERSION} \
            --tag ${IMAGE_BASE}:latest \
            --tag ${IMAGE_BASE_GHCR}:${VERSION} \
            --tag ${IMAGE_BASE_GHCR}:latest \
            .
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Push Docker image
        if: github.ref == 'refs/heads/master'
        run: |
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE_BASE}:latest
          docker push ${IMAGE_BASE}:${VERSION}
          docker login ghcr.io -u ${GHCR_PUSH_USERNAME} -p ${GHCR_PUSH_TOKEN}
          docker push ${IMAGE_BASE_GHCR}:latest
          docker push ${IMAGE_BASE_GHCR}:${VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHCR_PUSH_USERNAME: ${{ secrets.GHCR_PUSH_USERNAME }}
          GHCR_PUSH_TOKEN: ${{ secrets.GHCR_PUSH_TOKEN }}
          VERSION: ${{ env.VERSION }}
