name: Build vtp-pensjon docker image

on:
  push:
    branches:
      - vtp-pensjon-T4    # Push events on master branch
env:
  IMAGE_BASE: ghcr.io/${{ github.repository }}/vtp-pensjon-t4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build artifacts
        shell: bash
        run: |
          mvn clean install -Dfile.encoding=UTF-8

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          COMMIT=$(git rev-parse --short=12 HEAD)
          export VERSION="$TIME-$COMMIT"
          docker build --pull --tag ${IMAGE_BASE}:${VERSION} .
          docker push ${IMAGE_BASE}:${VERSION}
