name: Build vtp-pensjon docker image

on:
  push:
    branches:
      - vtp-pensjon-T4    # Push events on master branch
env:
  IMAGE_BASE: ghcr.io/${{ github.repository }}/vtp-pensjon

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - id: build
        run: |
          mvn package -B -Dfile.encoding=UTF-8

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=12 HEAD)
          export VERSION="$TIME-$COMMIT-t4-only"
          echo "Building ${IMAGE_BASE}:$VERSION"
          docker build --pull --tag ${IMAGE_BASE}:${VERSION} .
          docker push ${IMAGE_BASE}:${VERSION}
